var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/nos-bureaux/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5cc46263._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_c5ec60a4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ca69552d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a75edb7b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_nos-bureaux_page_actions_6d032e8e.js")
R.m(27580)
module.exports=R.m(27580).exports
